[package]
name = "test"
version = "0.1.0"
scarb-version = "2.11.4"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.4"
openzeppelin_utils = "2.0.0"

[dev-dependencies]
assert_macros = "2.11.4"
snforge_std = "0.46.0"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[workspace.tool.fmt]
sort-module-level-items = true

[tool]
fmt.workspace = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
